[package]
name = "rust-os"
version = "0.1.0"
authors = ["Arseniy Pendryak <a.pendryak@yandex.ru>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.9.4"
